name: Deploy to FTP SamrtHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Simple FTP
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: 'win6218.site4now.net'
          ftp_username: 'sageleo-001'
          ftp_password: 'KXmSbBt7CVoeBM'
          local_source_dir: '/'
          dist_target_dir: '/portfolio'
          delete: 'true'
